parent: classic
name: child_classic
display_name: Child theme of classic's theme
version: 1.0.0
assets:
  use_parent_assets: false

global_settings:
  hooks:
    modules_to_hook:
      displayNav1:
        - ps_contactinfo
      # displayNav2:
      #   - ps_languageselector
      #   - ps_currencyselector
      #   - ps_customersignin
      #   - ps_shoppingcart
