parent: classic
name: child_classic
display_name: Child theme of classic's theme
version: 1.0.0
assets:
  use_parent_assets: false

global_settings:
  hooks:
    modules_to_hook:
      # displayNav1:
      #   - ps_contactinfo
      displayNav2:
        # - ps_languageselector
        - ps_currencyselector
        - ps_customersignin
        # - ps_shoppingcart
      displayTop:
        # - ps_mainmenu
        - ps_searchbar
      displayMenu:
        - ps_mainmenu
      displayShoppingcart:
        - ps_shoppingcart
      displayFooterBefore:
        - ps_socialfollow
      displayHome:
        - ps_imageslider
        - ps_featuredproducts
      displayReassurance:
        - blockreassurance

  image_types:
    cart_default:
      width: 125
      height: 125
      scope: [products]
    small_default:
      width: 98
      height: 98
      scope: [products, categories, manufacturers, suppliers]
    medium_default:
      width: 452
      height: 452
      scope: [products, manufacturers, suppliers]
    home_default:
      width: 250
      height: 250
      scope: [products]
    large_default:
      width: 800
      height: 800
      scope: [products, manufacturers, suppliers]
    category_default:
      width: 141
      height: 180
      scope: [categories]
    stores_default:
      width: 170
      height: 115
      scope: [stores]
