services:
  mysql:
    image: mysql:5.7
    container_name: prestashop-db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: prestashop
      MYSQL_DATABASE: prestashop
    networks:
      - prestashop
    ports:
      - 3306:3306
    volumes:
      - dbdata:/var/lib/mysql

  prestashop:
    image: prestashop/prestashop:1.7.8
    container_name: prestashop
    environment:
      DB_PASSWD: prestashop
      DB_NAME: prestashop
      DB_PREFIX: ps_
      DB_SERVER: mysql
      DB_USER: root
      PS_COUNTRY: pl
      PS_DEV_MODE: 1
      ADMIN_MAIL: admin@admin.pl
      ADMIN_PASSWD: admin
      PS_FOLDER_ADMIN: admin2137
      PS_FOLDER_INSTALL: install2137
      PS_INSTALL_AUTO: 1
      PS_DOMAIN: localhost
    depends_on:
      - mysql
    networks:
      - prestashop
    volumes:
      - ../prestashop/themes/osiema:/var/www/html/themes/osiema
      - ../prestashop/themes/child_classic:/var/www/html/themes/child_classic
      - psdata:/var/www/html

  nginx:
    image: nginx:stable-alpine
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      - prestashop
    networks:
      - prestashop

networks:
  prestashop:

volumes:
  dbdata:
  psdata:
